// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yowmark/go-ent-pokemon/ent/battle"
	"github.com/yowmark/go-ent-pokemon/ent/pokemon"
	"github.com/yowmark/go-ent-pokemon/ent/predicate"
)

// BattleQuery is the builder for querying Battle entities.
type BattleQuery struct {
	config
	ctx           *QueryContext
	order         []OrderFunc
	inters        []Interceptor
	predicates    []predicate.Battle
	withContender *PokemonQuery
	withOponent   *PokemonQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BattleQuery builder.
func (bq *BattleQuery) Where(ps ...predicate.Battle) *BattleQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BattleQuery) Limit(limit int) *BattleQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BattleQuery) Offset(offset int) *BattleQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BattleQuery) Unique(unique bool) *BattleQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BattleQuery) Order(o ...OrderFunc) *BattleQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryContender chains the current query on the "contender" edge.
func (bq *BattleQuery) QueryContender() *PokemonQuery {
	query := (&PokemonClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battle.Table, battle.FieldID, selector),
			sqlgraph.To(pokemon.Table, pokemon.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, battle.ContenderTable, battle.ContenderColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOponent chains the current query on the "oponent" edge.
func (bq *BattleQuery) QueryOponent() *PokemonQuery {
	query := (&PokemonClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battle.Table, battle.FieldID, selector),
			sqlgraph.To(pokemon.Table, pokemon.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, battle.OponentTable, battle.OponentColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Battle entity from the query.
// Returns a *NotFoundError when no Battle was found.
func (bq *BattleQuery) First(ctx context.Context) (*Battle, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{battle.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BattleQuery) FirstX(ctx context.Context) *Battle {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Battle ID from the query.
// Returns a *NotFoundError when no Battle ID was found.
func (bq *BattleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{battle.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BattleQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Battle entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Battle entity is found.
// Returns a *NotFoundError when no Battle entities are found.
func (bq *BattleQuery) Only(ctx context.Context) (*Battle, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{battle.Label}
	default:
		return nil, &NotSingularError{battle.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BattleQuery) OnlyX(ctx context.Context) *Battle {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Battle ID in the query.
// Returns a *NotSingularError when more than one Battle ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BattleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{battle.Label}
	default:
		err = &NotSingularError{battle.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BattleQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Battles.
func (bq *BattleQuery) All(ctx context.Context) ([]*Battle, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Battle, *BattleQuery]()
	return withInterceptors[[]*Battle](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BattleQuery) AllX(ctx context.Context) []*Battle {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Battle IDs.
func (bq *BattleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err = bq.Select(battle.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BattleQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BattleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BattleQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BattleQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BattleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BattleQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BattleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BattleQuery) Clone() *BattleQuery {
	if bq == nil {
		return nil
	}
	return &BattleQuery{
		config:        bq.config,
		ctx:           bq.ctx.Clone(),
		order:         append([]OrderFunc{}, bq.order...),
		inters:        append([]Interceptor{}, bq.inters...),
		predicates:    append([]predicate.Battle{}, bq.predicates...),
		withContender: bq.withContender.Clone(),
		withOponent:   bq.withOponent.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithContender tells the query-builder to eager-load the nodes that are connected to
// the "contender" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BattleQuery) WithContender(opts ...func(*PokemonQuery)) *BattleQuery {
	query := (&PokemonClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withContender = query
	return bq
}

// WithOponent tells the query-builder to eager-load the nodes that are connected to
// the "oponent" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BattleQuery) WithOponent(opts ...func(*PokemonQuery)) *BattleQuery {
	query := (&PokemonClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withOponent = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Result string `json:"result,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Battle.Query().
//		GroupBy(battle.FieldResult).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (bq *BattleQuery) GroupBy(field string, fields ...string) *BattleGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BattleGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = battle.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Result string `json:"result,omitempty"`
//	}
//
//	client.Battle.Query().
//		Select(battle.FieldResult).
//		Scan(ctx, &v)
//
func (bq *BattleQuery) Select(fields ...string) *BattleSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BattleSelect{BattleQuery: bq}
	sbuild.label = battle.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BattleSelect configured with the given aggregations.
func (bq *BattleQuery) Aggregate(fns ...AggregateFunc) *BattleSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BattleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !battle.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BattleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Battle, error) {
	var (
		nodes       = []*Battle{}
		withFKs     = bq.withFKs
		_spec       = bq.querySpec()
		loadedTypes = [2]bool{
			bq.withContender != nil,
			bq.withOponent != nil,
		}
	)
	if bq.withContender != nil || bq.withOponent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, battle.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Battle).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Battle{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withContender; query != nil {
		if err := bq.loadContender(ctx, query, nodes, nil,
			func(n *Battle, e *Pokemon) { n.Edges.Contender = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withOponent; query != nil {
		if err := bq.loadOponent(ctx, query, nodes, nil,
			func(n *Battle, e *Pokemon) { n.Edges.Oponent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BattleQuery) loadContender(ctx context.Context, query *PokemonQuery, nodes []*Battle, init func(*Battle), assign func(*Battle, *Pokemon)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Battle)
	for i := range nodes {
		if nodes[i].pokemon_fights == nil {
			continue
		}
		fk := *nodes[i].pokemon_fights
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pokemon.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pokemon_fights" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BattleQuery) loadOponent(ctx context.Context, query *PokemonQuery, nodes []*Battle, init func(*Battle), assign func(*Battle, *Pokemon)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Battle)
	for i := range nodes {
		if nodes[i].pokemon_opponents == nil {
			continue
		}
		fk := *nodes[i].pokemon_opponents
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pokemon.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pokemon_opponents" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bq *BattleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BattleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(battle.Table, battle.Columns, sqlgraph.NewFieldSpec(battle.FieldID, field.TypeInt))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, battle.FieldID)
		for i := range fields {
			if fields[i] != battle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BattleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(battle.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = battle.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BattleGroupBy is the group-by builder for Battle entities.
type BattleGroupBy struct {
	selector
	build *BattleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BattleGroupBy) Aggregate(fns ...AggregateFunc) *BattleGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BattleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BattleQuery, *BattleGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BattleGroupBy) sqlScan(ctx context.Context, root *BattleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BattleSelect is the builder for selecting fields of Battle entities.
type BattleSelect struct {
	*BattleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BattleSelect) Aggregate(fns ...AggregateFunc) *BattleSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BattleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BattleQuery, *BattleSelect](ctx, bs.BattleQuery, bs, bs.inters, v)
}

func (bs *BattleSelect) sqlScan(ctx context.Context, root *BattleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
