// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yowmark/go-ent-pokemon/ent/battle"
	"github.com/yowmark/go-ent-pokemon/ent/pokemon"
	"github.com/yowmark/go-ent-pokemon/ent/predicate"
)

// BattleUpdate is the builder for updating Battle entities.
type BattleUpdate struct {
	config
	hooks    []Hook
	mutation *BattleMutation
}

// Where appends a list predicates to the BattleUpdate builder.
func (bu *BattleUpdate) Where(ps ...predicate.Battle) *BattleUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetResult sets the "result" field.
func (bu *BattleUpdate) SetResult(s string) *BattleUpdate {
	bu.mutation.SetResult(s)
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BattleUpdate) SetUpdatedAt(t time.Time) *BattleUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bu *BattleUpdate) SetNillableUpdatedAt(t *time.Time) *BattleUpdate {
	if t != nil {
		bu.SetUpdatedAt(*t)
	}
	return bu
}

// SetContenderID sets the "contender" edge to the Pokemon entity by ID.
func (bu *BattleUpdate) SetContenderID(id int) *BattleUpdate {
	bu.mutation.SetContenderID(id)
	return bu
}

// SetNillableContenderID sets the "contender" edge to the Pokemon entity by ID if the given value is not nil.
func (bu *BattleUpdate) SetNillableContenderID(id *int) *BattleUpdate {
	if id != nil {
		bu = bu.SetContenderID(*id)
	}
	return bu
}

// SetContender sets the "contender" edge to the Pokemon entity.
func (bu *BattleUpdate) SetContender(p *Pokemon) *BattleUpdate {
	return bu.SetContenderID(p.ID)
}

// SetOponentID sets the "oponent" edge to the Pokemon entity by ID.
func (bu *BattleUpdate) SetOponentID(id int) *BattleUpdate {
	bu.mutation.SetOponentID(id)
	return bu
}

// SetNillableOponentID sets the "oponent" edge to the Pokemon entity by ID if the given value is not nil.
func (bu *BattleUpdate) SetNillableOponentID(id *int) *BattleUpdate {
	if id != nil {
		bu = bu.SetOponentID(*id)
	}
	return bu
}

// SetOponent sets the "oponent" edge to the Pokemon entity.
func (bu *BattleUpdate) SetOponent(p *Pokemon) *BattleUpdate {
	return bu.SetOponentID(p.ID)
}

// Mutation returns the BattleMutation object of the builder.
func (bu *BattleUpdate) Mutation() *BattleMutation {
	return bu.mutation
}

// ClearContender clears the "contender" edge to the Pokemon entity.
func (bu *BattleUpdate) ClearContender() *BattleUpdate {
	bu.mutation.ClearContender()
	return bu
}

// ClearOponent clears the "oponent" edge to the Pokemon entity.
func (bu *BattleUpdate) ClearOponent() *BattleUpdate {
	bu.mutation.ClearOponent()
	return bu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BattleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, BattleMutation](ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BattleUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BattleUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BattleUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BattleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(battle.Table, battle.Columns, sqlgraph.NewFieldSpec(battle.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Result(); ok {
		_spec.SetField(battle.FieldResult, field.TypeString, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(battle.FieldUpdatedAt, field.TypeTime, value)
	}
	if bu.mutation.ContenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.ContenderTable,
			Columns: []string{battle.ContenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.ContenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.ContenderTable,
			Columns: []string{battle.ContenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.OponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.OponentTable,
			Columns: []string{battle.OponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.OponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.OponentTable,
			Columns: []string{battle.OponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{battle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BattleUpdateOne is the builder for updating a single Battle entity.
type BattleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BattleMutation
}

// SetResult sets the "result" field.
func (buo *BattleUpdateOne) SetResult(s string) *BattleUpdateOne {
	buo.mutation.SetResult(s)
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BattleUpdateOne) SetUpdatedAt(t time.Time) *BattleUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (buo *BattleUpdateOne) SetNillableUpdatedAt(t *time.Time) *BattleUpdateOne {
	if t != nil {
		buo.SetUpdatedAt(*t)
	}
	return buo
}

// SetContenderID sets the "contender" edge to the Pokemon entity by ID.
func (buo *BattleUpdateOne) SetContenderID(id int) *BattleUpdateOne {
	buo.mutation.SetContenderID(id)
	return buo
}

// SetNillableContenderID sets the "contender" edge to the Pokemon entity by ID if the given value is not nil.
func (buo *BattleUpdateOne) SetNillableContenderID(id *int) *BattleUpdateOne {
	if id != nil {
		buo = buo.SetContenderID(*id)
	}
	return buo
}

// SetContender sets the "contender" edge to the Pokemon entity.
func (buo *BattleUpdateOne) SetContender(p *Pokemon) *BattleUpdateOne {
	return buo.SetContenderID(p.ID)
}

// SetOponentID sets the "oponent" edge to the Pokemon entity by ID.
func (buo *BattleUpdateOne) SetOponentID(id int) *BattleUpdateOne {
	buo.mutation.SetOponentID(id)
	return buo
}

// SetNillableOponentID sets the "oponent" edge to the Pokemon entity by ID if the given value is not nil.
func (buo *BattleUpdateOne) SetNillableOponentID(id *int) *BattleUpdateOne {
	if id != nil {
		buo = buo.SetOponentID(*id)
	}
	return buo
}

// SetOponent sets the "oponent" edge to the Pokemon entity.
func (buo *BattleUpdateOne) SetOponent(p *Pokemon) *BattleUpdateOne {
	return buo.SetOponentID(p.ID)
}

// Mutation returns the BattleMutation object of the builder.
func (buo *BattleUpdateOne) Mutation() *BattleMutation {
	return buo.mutation
}

// ClearContender clears the "contender" edge to the Pokemon entity.
func (buo *BattleUpdateOne) ClearContender() *BattleUpdateOne {
	buo.mutation.ClearContender()
	return buo
}

// ClearOponent clears the "oponent" edge to the Pokemon entity.
func (buo *BattleUpdateOne) ClearOponent() *BattleUpdateOne {
	buo.mutation.ClearOponent()
	return buo
}

// Where appends a list predicates to the BattleUpdate builder.
func (buo *BattleUpdateOne) Where(ps ...predicate.Battle) *BattleUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BattleUpdateOne) Select(field string, fields ...string) *BattleUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Battle entity.
func (buo *BattleUpdateOne) Save(ctx context.Context) (*Battle, error) {
	return withHooks[*Battle, BattleMutation](ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BattleUpdateOne) SaveX(ctx context.Context) *Battle {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BattleUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BattleUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BattleUpdateOne) sqlSave(ctx context.Context) (_node *Battle, err error) {
	_spec := sqlgraph.NewUpdateSpec(battle.Table, battle.Columns, sqlgraph.NewFieldSpec(battle.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Battle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, battle.FieldID)
		for _, f := range fields {
			if !battle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != battle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Result(); ok {
		_spec.SetField(battle.FieldResult, field.TypeString, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(battle.FieldUpdatedAt, field.TypeTime, value)
	}
	if buo.mutation.ContenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.ContenderTable,
			Columns: []string{battle.ContenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.ContenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.ContenderTable,
			Columns: []string{battle.ContenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.OponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.OponentTable,
			Columns: []string{battle.OponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.OponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.OponentTable,
			Columns: []string{battle.OponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Battle{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{battle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
