// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yowmark/go-ent-pokemon/ent/battle"
	"github.com/yowmark/go-ent-pokemon/ent/pokemon"
	"github.com/yowmark/go-ent-pokemon/ent/predicate"
)

// PokemonQuery is the builder for querying Pokemon entities.
type PokemonQuery struct {
	config
	ctx           *QueryContext
	order         []OrderFunc
	inters        []Interceptor
	predicates    []predicate.Pokemon
	withFights    *BattleQuery
	withOpponents *BattleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PokemonQuery builder.
func (pq *PokemonQuery) Where(ps ...predicate.Pokemon) *PokemonQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PokemonQuery) Limit(limit int) *PokemonQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PokemonQuery) Offset(offset int) *PokemonQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PokemonQuery) Unique(unique bool) *PokemonQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PokemonQuery) Order(o ...OrderFunc) *PokemonQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryFights chains the current query on the "fights" edge.
func (pq *PokemonQuery) QueryFights() *BattleQuery {
	query := (&BattleClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pokemon.Table, pokemon.FieldID, selector),
			sqlgraph.To(battle.Table, battle.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pokemon.FightsTable, pokemon.FightsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOpponents chains the current query on the "opponents" edge.
func (pq *PokemonQuery) QueryOpponents() *BattleQuery {
	query := (&BattleClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pokemon.Table, pokemon.FieldID, selector),
			sqlgraph.To(battle.Table, battle.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pokemon.OpponentsTable, pokemon.OpponentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Pokemon entity from the query.
// Returns a *NotFoundError when no Pokemon was found.
func (pq *PokemonQuery) First(ctx context.Context) (*Pokemon, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pokemon.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PokemonQuery) FirstX(ctx context.Context) *Pokemon {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Pokemon ID from the query.
// Returns a *NotFoundError when no Pokemon ID was found.
func (pq *PokemonQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pokemon.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PokemonQuery) FirstIDX(ctx context.Context) int {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Pokemon entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Pokemon entity is found.
// Returns a *NotFoundError when no Pokemon entities are found.
func (pq *PokemonQuery) Only(ctx context.Context) (*Pokemon, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pokemon.Label}
	default:
		return nil, &NotSingularError{pokemon.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PokemonQuery) OnlyX(ctx context.Context) *Pokemon {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Pokemon ID in the query.
// Returns a *NotSingularError when more than one Pokemon ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PokemonQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pokemon.Label}
	default:
		err = &NotSingularError{pokemon.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PokemonQuery) OnlyIDX(ctx context.Context) int {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Pokemons.
func (pq *PokemonQuery) All(ctx context.Context) ([]*Pokemon, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Pokemon, *PokemonQuery]()
	return withInterceptors[[]*Pokemon](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PokemonQuery) AllX(ctx context.Context) []*Pokemon {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Pokemon IDs.
func (pq *PokemonQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err = pq.Select(pokemon.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PokemonQuery) IDsX(ctx context.Context) []int {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PokemonQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PokemonQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PokemonQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PokemonQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PokemonQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PokemonQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PokemonQuery) Clone() *PokemonQuery {
	if pq == nil {
		return nil
	}
	return &PokemonQuery{
		config:        pq.config,
		ctx:           pq.ctx.Clone(),
		order:         append([]OrderFunc{}, pq.order...),
		inters:        append([]Interceptor{}, pq.inters...),
		predicates:    append([]predicate.Pokemon{}, pq.predicates...),
		withFights:    pq.withFights.Clone(),
		withOpponents: pq.withOpponents.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithFights tells the query-builder to eager-load the nodes that are connected to
// the "fights" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PokemonQuery) WithFights(opts ...func(*BattleQuery)) *PokemonQuery {
	query := (&BattleClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withFights = query
	return pq
}

// WithOpponents tells the query-builder to eager-load the nodes that are connected to
// the "opponents" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PokemonQuery) WithOpponents(opts ...func(*BattleQuery)) *PokemonQuery {
	query := (&BattleClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withOpponents = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Pokemon.Query().
//		GroupBy(pokemon.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pq *PokemonQuery) GroupBy(field string, fields ...string) *PokemonGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PokemonGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = pokemon.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Pokemon.Query().
//		Select(pokemon.FieldName).
//		Scan(ctx, &v)
//
func (pq *PokemonQuery) Select(fields ...string) *PokemonSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PokemonSelect{PokemonQuery: pq}
	sbuild.label = pokemon.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PokemonSelect configured with the given aggregations.
func (pq *PokemonQuery) Aggregate(fns ...AggregateFunc) *PokemonSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PokemonQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !pokemon.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PokemonQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Pokemon, error) {
	var (
		nodes       = []*Pokemon{}
		_spec       = pq.querySpec()
		loadedTypes = [2]bool{
			pq.withFights != nil,
			pq.withOpponents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Pokemon).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Pokemon{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withFights; query != nil {
		if err := pq.loadFights(ctx, query, nodes,
			func(n *Pokemon) { n.Edges.Fights = []*Battle{} },
			func(n *Pokemon, e *Battle) { n.Edges.Fights = append(n.Edges.Fights, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withOpponents; query != nil {
		if err := pq.loadOpponents(ctx, query, nodes,
			func(n *Pokemon) { n.Edges.Opponents = []*Battle{} },
			func(n *Pokemon, e *Battle) { n.Edges.Opponents = append(n.Edges.Opponents, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PokemonQuery) loadFights(ctx context.Context, query *BattleQuery, nodes []*Pokemon, init func(*Pokemon), assign func(*Pokemon, *Battle)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Pokemon)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Battle(func(s *sql.Selector) {
		s.Where(sql.InValues(pokemon.FightsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.pokemon_fights
		if fk == nil {
			return fmt.Errorf(`foreign-key "pokemon_fights" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pokemon_fights" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PokemonQuery) loadOpponents(ctx context.Context, query *BattleQuery, nodes []*Pokemon, init func(*Pokemon), assign func(*Pokemon, *Battle)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Pokemon)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Battle(func(s *sql.Selector) {
		s.Where(sql.InValues(pokemon.OpponentsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.pokemon_opponents
		if fk == nil {
			return fmt.Errorf(`foreign-key "pokemon_opponents" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pokemon_opponents" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (pq *PokemonQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PokemonQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pokemon.Table, pokemon.Columns, sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pokemon.FieldID)
		for i := range fields {
			if fields[i] != pokemon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PokemonQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(pokemon.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = pokemon.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PokemonGroupBy is the group-by builder for Pokemon entities.
type PokemonGroupBy struct {
	selector
	build *PokemonQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PokemonGroupBy) Aggregate(fns ...AggregateFunc) *PokemonGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PokemonGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PokemonQuery, *PokemonGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PokemonGroupBy) sqlScan(ctx context.Context, root *PokemonQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PokemonSelect is the builder for selecting fields of Pokemon entities.
type PokemonSelect struct {
	*PokemonQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PokemonSelect) Aggregate(fns ...AggregateFunc) *PokemonSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PokemonSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PokemonQuery, *PokemonSelect](ctx, ps.PokemonQuery, ps, ps.inters, v)
}

func (ps *PokemonSelect) sqlScan(ctx context.Context, root *PokemonQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
