// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yowmark/go-ent-pokemon/ent/pokemon"
	"github.com/yowmark/go-ent-pokemon/ent/predicate"
)

// PokemonDelete is the builder for deleting a Pokemon entity.
type PokemonDelete struct {
	config
	hooks    []Hook
	mutation *PokemonMutation
}

// Where appends a list predicates to the PokemonDelete builder.
func (pd *PokemonDelete) Where(ps ...predicate.Pokemon) *PokemonDelete {
	pd.mutation.Where(ps...)
	return pd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pd *PokemonDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, PokemonMutation](ctx, pd.sqlExec, pd.mutation, pd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pd *PokemonDelete) ExecX(ctx context.Context) int {
	n, err := pd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pd *PokemonDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pokemon.Table, sqlgraph.NewFieldSpec(pokemon.FieldID, field.TypeInt))
	if ps := pd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pd.mutation.done = true
	return affected, err
}

// PokemonDeleteOne is the builder for deleting a single Pokemon entity.
type PokemonDeleteOne struct {
	pd *PokemonDelete
}

// Where appends a list predicates to the PokemonDelete builder.
func (pdo *PokemonDeleteOne) Where(ps ...predicate.Pokemon) *PokemonDeleteOne {
	pdo.pd.mutation.Where(ps...)
	return pdo
}

// Exec executes the deletion query.
func (pdo *PokemonDeleteOne) Exec(ctx context.Context) error {
	n, err := pdo.pd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pokemon.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdo *PokemonDeleteOne) ExecX(ctx context.Context) {
	if err := pdo.Exec(ctx); err != nil {
		panic(err)
	}
}
